#!/usr/bin/env python3

from rqt_gui.main import Main
from motion_system_rqt.motion_system_controller import MotionSystemController

import sys


plugin = 'motion_system_rqt.motion_system_controller.MotionSystemController'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))